name: 'Docker Build & Push for Storefront'
description: 'Docker Build & Push for Storefront'

inputs:
  GITHUB_TOKEN:
    description: 'github token needed for docker credentials'
    required: true

  DOCKER_REPOSITORY:
    description: 'docker image repository'
    required: true

  DOCKER_TAG:
    description: 'docker image tag'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Github actions
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: '${{ github.actor }}'
        password: '${{ inputs.GITHUB_TOKEN }}'

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ inputs.DOCKER_REPOSITORY }}:${{ inputs.DOCKER_TAG }}
        file: apps/storefront/Dockerfile
