name: Lint and Type Check

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_CACHE: "remote:rw"

jobs:
  lint:
    runs-on: warp-ubuntu-2404-x64-2x
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run Biome
        run: biome ci .

  typecheck:
    runs-on: warp-ubuntu-2404-x64-2x
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache turbo build setup
        if: env.skip == 'false'
        uses: WarpBuilds/cache@v1
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: WarpBuilds/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Type-check
        if: ${{ needs.detect-changes.outputs.e2e == 'true' }}
        run: yarn typecheck

      - name: Build
        run: yarn build
      
